GET http://localhost:3000
###


POST http://localhost:3000/persons
Content-Type:  application/json

{
    "name": "",
    "number": "2345"
}


###
POST http://localhost:3000/test
Content-Type: application/json 

{
    "name": "New Person",
    "number": "1234",
    "id": null
}